const shopData = [
  {
    title: "Hats",
    items: [
      {
        id: 1,
        name: "Brown Sun Hat",
        imageUrl: "https://i.imgur.com/hBSAcrN.jpeg",
        price: 25,
        quantity: 5,
      },
      {
        id: 2,
        name: "Red Beanie",
        imageUrl: "https://i.imgur.com/leDq3iI.jpeg",
        price: 18,
        quantity: 8,
      },
      {
        id: 3,
        name: "Brown Cowboy Hat",
        imageUrl: "https://i.imgur.com/KeHlTlx.jpeg",
        price: 35,
        quantity: 13,
      },
      {
        id: 4,
        name: "Black Fedora",
        imageUrl: "https://i.imgur.com/lqIGtVP.jpeg",
        price: 25,
        quantity: 3,
      },
      {
        id: 5,
        name: "Green Beanie",
        imageUrl: "https://i.imgur.com/5Ntztkl.jpeg",
        price: 18,
        quantity: 4,
      },
      {
        id: 6,
        name: "Ushanka Hat",
        imageUrl: "https://i.imgur.com/PE7kGr0.jpg",
        price: 14,
        quantity: 10,
      },
      {
        id: 7,
        name: "Black Flat Cap",
        imageUrl: "https://i.imgur.com/tvHZgWJ.jpeg",
        price: 18,
        quantity: 9,
      },
      {
        id: 8,
        name: "Baseball Cap",
        imageUrl: "https://i.imgur.com/gduwIM0.jpeg",
        price: 14,
        quantity: 53,
      },
      {
        id: 9,
        name: "Black Snapback",
        imageUrl: "https://i.imgur.com/LFM09Aw.jpeg",
        price: 16,
        quantity: 17,
      },
    ],
  },
  {
    title: "Jackets",
    items: [
      {
        id: 10,
        name: "Blue Denim Jacket",
        imageUrl: "src/images/Jackets/10-blue-denim-jacket.jpg",
        price: 125,
        quantity: 24,
      },
      {
        id: 11,
        name: "Yellow Rain Coat",
        imageUrl: "src/images/Jackets/11-yellow-rain-coat.jpg",
        price: 90,
        quantity: 82,
      },
      {
        id: 12,
        name: "Brown Jacket",
        imageUrl: "src/images/Jackets/12-brown-jacket.jpg",
        price: 142,
        quantity: 93,
      },
      {
        id: 13,
        name: "Brown Shearling",
        imageUrl: "src/images/Jackets/13-brown-shearling.jpg",
        price: 165,
        quantity: 120,
      },
      {
        id: 14,
        name: "Leather Jacket",
        imageUrl: "src/images/Jackets/14-leather-jacket.jpg",
        price: 185,
        quantity: 243,
      },
      {
        id: 15,
        name: "Trench Coat",
        imageUrl: "src/images/Jackets/15-trench-coat.jpg",
        price: 285,
        quantity: 148,
      },
      {
        id: 16,
        name: "Varsity Jacket",
        imageUrl: "src/images/Jackets/16-varsity-jacket.jpg",
        price: 185,
        quantity: 24,
      },
      {
        id: 17,
        name: "Brown Jacket",
        imageUrl: "src/images/Jackets/17-brown-jacket.jpg",
        price: 250,
        quantity: 82,
      },
      {
        id: 18,
        name: "Brown Topcoat",
        imageUrl: "src/images/Jackets/18-brown-topcoat.jpg",
        price: 200,
        quantity: 93,
      },
    ],
  },
  {
    title: "Sneakers",
    items: [
      {
        id: 19,
        name: "Adidas NMD",
        imageUrl: "https://i.ibb.co/0s3pdnc/adidas-nmd.png",
        price: 220,
      },
      {
        id: 20,
        name: "Adidas Yeezy",
        imageUrl: "https://i.ibb.co/dJbG1cT/yeezy.png",
        price: 280,
      },
      {
        id: 21,
        name: "Black Converse",
        imageUrl: "https://i.ibb.co/bPmVXyP/black-converse.png",
        price: 110,
      },
      {
        id: 22,
        name: "Nike White AirForce",
        imageUrl: "https://i.ibb.co/1RcFPk0/white-nike-high-tops.png",
        price: 160,
      },
      {
        id: 23,
        name: "Nike Red High Tops",
        imageUrl: "https://i.ibb.co/QcvzydB/nikes-red.png",
        price: 160,
      },
      {
        id: 24,
        name: "Nike Brown High Tops",
        imageUrl: "https://i.ibb.co/fMTV342/nike-brown.png",
        price: 160,
      },
      {
        id: 25,
        name: "Air Jordan Limited",
        imageUrl: "https://i.ibb.co/w4k6Ws9/nike-funky.png",
        price: 190,
      },
      {
        id: 26,
        name: "Timberlands",
        imageUrl: "https://i.ibb.co/Mhh6wBg/timberlands.png",
        price: 200,
      },
      {
        id: 27,
        name: "Timberlands",
        imageUrl: "https://i.ibb.co/Mhh6wBg/timberlands.png",
        price: 200,
      },
    ],
  },
];

export default shopData;
